### ISSUE TITLE
Error -43001

### ISSUE THREAD

**Issue by matinkaboli** [nknorg/nkn-wallet-js#20]
Hi,

I'm using this package to interact width NKN and when I use this code:

```javascript
wallet.registerName('MATINMATIN', 'myPassword')
```

It throws an error and says:

```javascript
{code: -43001, message: "INVALID TRANSACTION"}
```

"nkn-wallet": "^0.2.0",
node: v10.15.0

**Comment by CrackDavid** [comment]
Sorry to answer this late - I can only tell from my experience.
The WalletName has to be

1. only letters
2. length between 8 and 12 characters
3. all lowercase

I would assume if you try to register your name with ``matinmatin`` it'll work.

**Comment by matinkaboli** [comment]
Yes you're right, it works fine now.
